# Site settings
name: David M. Lo
email: pramslam@gmail.com
#canonical_url: http://www.dlogames.com
keywords: "Software Engineer, C++, C#, Unity, Unreal Engine 4, Startups, Agile, Pair Programming"
skills: "Gameplay Programmer in Eugene, OR"
baseurl:

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# You should replace these with your social networks, of course. :)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/mrdavidmlo/
  - title: facebook
    url: https://www.facebook.com/pramslam
    
# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 2196F3
  primary-rgb: "33, 150, 243"
  secondary: 285172
  secondary-dark: 29455b
  section-tout: eaf1f1

# Build settings
markdown: kramdown
permalink: pretty
